// Runtime environment configuration helper
// In development: uses import.meta.env (Vite)
// In production: uses window.__ENV__ (generated by entrypoint.sh)

interface RuntimeEnv {
    VITE_API_BASE_URL: string;
}

declare global {
    interface Window {
        __ENV__?: RuntimeEnv;
    }
}

export function getEnv(key: keyof RuntimeEnv): string {
    // First check runtime env (production with Docker)
    if (typeof window !== 'undefined' && window.__ENV__ && window.__ENV__[key]) {
        return window.__ENV__[key];
    }

    // Fallback to Vite env (development)
    const viteEnv = import.meta.env[key];
    if (viteEnv) {
        return viteEnv;
    }

    // Default fallbacks
    const defaults: RuntimeEnv = {
        VITE_API_BASE_URL: 'http://localhost:8000',
    };

    return defaults[key];
}

export const API_BASE_URL = getEnv('VITE_API_BASE_URL');
